# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# 

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

default_platform(:ios)

platform :ios do
  desc "iOS 自动打包"
  lane :Project_Debug_NotDingDing do |options|

    scheme_name = "Project"

    output_directory = "./debug/"

    #increment_build_number

    #version = get_version_number(xcodeproj: "Project.xcodeproj", target: "#{scheme_name}")

    buildNumber = get_build_number

    output_name = "#{scheme_name}_#{buildNumber}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"

    gym(scheme: scheme_name,
            workspace: "Project.xcworkspace",
            include_bitcode: false,
            configuration: "Debug",
	    include_symbols: true,
	    export_method: "development",
	    output_directory: output_directory,
	    build_path: output_directory,
	    archive_path: output_directory,
	    output_name: output_name)
    branchName = options[:branchName]
    jobName = options[:jobName]
    changeLog = options[:changeLog]
    answer = fir_cli api_token:"xxxxxxxxx", need_release_id: true
 
    puts "上传后的结果：#{answer}"

    download_url = "http://hey.appc01.com/#{answer[:short]}?release_id=#{answer[:release_id]}"

    dingdingMsg = "Debug #{branchName} 下载:#{download_url} \n 修改日志:#{changeLog} \n"
    puts "打包结束时，输出文案：#{dingdingMsg}"

    fir_cli api_token:"xxxxxxxx", changelog: dingdingMsg
    
  end

  lane :Project_Debug do |options|

    scheme_name = "Project"

    output_directory = "./debug/"

    #increment_build_number

    #version = get_version_number(xcodeproj: "Project.xcodeproj", target: "#{scheme_name}")

    buildNumber = get_build_number

    output_name = "#{scheme_name}_#{buildNumber}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"

    gym(scheme: scheme_name,
            workspace: "Project.xcworkspace",
            include_bitcode: false,
            configuration: "Debug",
	    include_symbols: true,
	    export_method: "development",
	    output_directory: output_directory,
	    build_path: output_directory,
	    archive_path: output_directory,
	    output_name: output_name)
    branchName = options[:branchName]
    jobName = options[:jobName]
    changeLog = options[:changeLog] 

    # 截断字符，因为钉钉消息体有限制：{"errcode":460101,"errmsg":"description: body 大小不合法;solution:请保持大小在 20000bytes 以内;"}
    if changeLog.length > 500
      changeLog = changeLog[0,497]
      changeLog = "#{changeLog}..."
    end
	  
    answer = fir_cli api_token:"xxxxxxxxxxx", need_release_id: true
 
    puts "上传后的结果：#{answer}"

    download_url = "https://hey.appc01.com/#{answer[:short]}?release_id=#{answer[:release_id]}"

    dingdingMsg = "打包结果通知：Jenkins 打包成功。Debug 开发包。\n branchName:#{branchName}\n jobName:#{jobName}\n 下载二维码链接:#{download_url} \n 修改日志:#{changeLog} \n"
    puts "打包结束时，输出文案：#{dingdingMsg}"

    #fir_cli api_token:"xxxxxx", dingtalk_at_all: true, #dingtalk_access_token:"xxxxxxx", #dingtalk_custom_message: dingdingMsg
    
    dingTalk_url = "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx"

    # 构造消息格式
    text = {
      "at": {
        "isAtAll": true
      },
      "text": {
          "content": "#{dingdingMsg}"
      }, 
      "msgtype": "text"
    }

    puts "发送的钉钉消息：#{text} "

    uri = URI.parse(dingTalk_url)
    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true

    request = Net::HTTP::Post.new(uri.request_uri)
    request.add_field('Content-Type', 'application/json')
    request.body = text.to_json

    response = https.request(request)
    puts "------------------------------"
    puts "Response #{response.code} #{response.message}: #{response.body}"
  end

  lane :Project_Release do |options|
    scheme_name = "Project"

    output_directory = "./release/"

    #increment_build_number

    #version = get_version_number(xcodeproj: "Project.xcodeproj", target: "#{scheme_name}")

    buildNumber = get_build_number

    output_name = "#{scheme_name}_#{buildNumber}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"

    gym(scheme: scheme_name,
            workspace: "Project.xcworkspace",
            include_bitcode: false,
            configuration: "Release",
	    include_symbols: true,
	    export_method: "development",
	    output_directory: output_directory,
	    build_path: output_directory,
	    archive_path: output_directory,
	    output_name: output_name)
    branchName = options[:branchName]
    jobName = options[:jobName]
    changeLog = options[:changeLog]
	  
    # 截断字符，因为钉钉消息体有限制：{"errcode":460101,"errmsg":"description: body 大小不合法;solution:请保持大小在 20000bytes 以内;"}
    if changeLog.length > 500
      changeLog = changeLog[0,497]
      changeLog = "#{changeLog}..."
    end
	  
    answer = fir_cli api_token:"xxxxxxx", need_release_id: true
 
    puts "上传后的结果：#{answer}"

    download_url = "https://hey.appc01.com/#{answer[:short]}?release_id=#{answer[:release_id]}"

    dingdingMsg = "打包结果通知：Jenkins 打包成功。Release 线上包。\n branchName:#{branchName}\n jobName:#{jobName}\n 下载二维码链接:#{download_url} \n 修改日志:#{changeLog} \n"
    puts "打包结束时，输出文案：#{dingdingMsg}"

    #fir_cli api_token:"xxxxxx", dingtalk_at_all: true, #dingtalk_access_token:"xxxxxx", #dingtalk_custom_message: dingdingMsg
    
    dingTalk_url = "https://oapi.dingtalk.com/robot/send?access_token=xxxxx"

    # 构造消息格式
    text = {
      "at": {
        "isAtAll": true
      },
      "text": {
          "content": "#{dingdingMsg}"
      }, 
      "msgtype": "text"
    }

    puts "发送的钉钉消息：#{text} "

    uri = URI.parse(dingTalk_url)
    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true

    request = Net::HTTP::Post.new(uri.request_uri)
    request.add_field('Content-Type', 'application/json')
    request.body = text.to_json

    response = https.request(request)
    puts "------------------------------"
    puts "Response #{response.code} #{response.message}: #{response.body}"
  end

  lane :Project_AppStore do
    build_app(scheme: "Project",
            workspace: "Project.xcworkspace",
            include_bitcode: false,
            configuration: "Release",
	    include_symbols: true,
	    export_method: "app-store",
	    output_directory: "~/Release/",
	    build_path: "~/Release/",
	    archive_path: "~/Release/")
    branchName = options[:branchName]
    jobName = options[:jobName]

    answer = fir_cli api_token:"xxxxxxx", need_release_id: true
 
    puts "上传后的结果：#{answer}"

    download_url = "https://hey.appc01.com/#{answer[:short]}?release_id=#{answer[:release_id]}"

    dingdingMsg = "打包结果通知：Jenkins 打包成功。Release branchName:#{branchName} jobName:#{jobName} 下载二维码链接:#{download_url}"
    puts "打包结束时，输出文案：#{dingdingMsg}"

    fir_cli api_token:"xxxxx", dingtalk_at_all: true, dingtalk_access_token:"xxxxx", dingtalk_custom_message: dingdingMsg
  end

end
